/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_kb_jp2_Jp2Decode */

#ifndef _Included_nl_kb_jp2_Jp2Decode
#define _Included_nl_kb_jp2_Jp2Decode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_kb_jp2_Jp2Decode
 * Method:    decodeJp2Area
 * Signature: (Ljava/lang/String;IIIII[[I)Lnl/kb/jp2/DecodedImageDims;
 */
JNIEXPORT jobject JNICALL Java_nl_kb_jp2_Jp2Decode_decodeJp2Area
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
