/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_kb_jp2_Jp2Header */

#ifndef _Included_nl_kb_jp2_Jp2Header
#define _Included_nl_kb_jp2_Jp2Header
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_kb_jp2_Jp2Header
 * Method:    fromFile
 * Signature: (Ljava/lang/String;)Lnl/kb/jp2/Jp2Header;
 */
JNIEXPORT jobject JNICALL Java_nl_kb_jp2_Jp2Header_fromFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
